language: python
sudo: false
branches:
  only:
    - master
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - "pypy"
env:
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"
matrix:
  exclude:
    - python: 3.3
      env: DJANGO="Django>=1.9,<1.10"
    - python: 3.3
      env: DJANGO="Django>=1.10,<1.11"
install:
  - pip install -q -U pip
  - pip install -q -r tests/REQUIREMENTS.txt
  - pip install -q $DJANGO
  - nvm install 7
script:
  - PYTHONPATH=.:example py.test tests/
  - cd node && npm install --progress=false && npm test
