language: python
sudo: false
services:
  - redis-server
branches:
  only:
    - master
python:
  - 3.6
  - 3.7
  - "pypy3"
env:
  - DJANGO="Django>=2,<3"
install:
  - pip install -q -U pip
  - pip install -q -r tests/REQUIREMENTS.txt
  - pip install -q $DJANGO
  - nvm install 12
script:
  - PYTHONPATH=.:example py.test tests/
  - cd node && npm install --progress=false && npm test
