language: python
sudo: false
branches:
  only:
    - master
python:
  - 3.5
  - 3.6
  - "pypy3"
env:
  - DJANGO="Django>=1.10,<1.11"
  - DJANGO="Django>=1.11,<2"
install:
  - pip install -q -U pip
  - pip install -q -r tests/REQUIREMENTS.txt
  - pip install -q $DJANGO
  - nvm install 7
script:
  - PYTHONPATH=.:example py.test tests/
  - cd node && npm install --progress=false && npm test
